### ISSUE TITLE
fetching ff values with SDK failed

### ISSUE THREAD

**Issue by hodamarr** [featurehub-io/featurehub-python-sdk#22]
Hello, I use FeatureHub for several services. I've built a microservice acting as a Python WSGI-based proxy. The feature values are mostly consts. I do not need an open stream to receive and update information because in my larger services, I use a caching mechanism for the feature values.

I'm encountering a lot of ongoing crash logs
`Traceback (most recent call last):
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/pythonjsonlogger/jsonlogger.py", line 226, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/featurehub_sdk/streaming_edge_service.py", line 61, in run
    log.error("failed to communicate with featurehub", err)
Message: 'failed to communicate with featurehub'
Arguments: (ProtocolError("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read)),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
                      ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/featurehub_sdk/streaming_edge_service.py", line 46, in run
    for event in self._client.events():
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/sseclient/__init__.py", line 58, in events
    for chunk in self._read():
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/sseclient/__init__.py", line 48, in _read
    for chunk in self._event_source:
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 872, in __iter__
    for chunk in self.stream(decode_content=True):
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/concurrent_log_handler/__init__.py", line 380, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/featurehub_sdk/streaming_edge_service.py", line 61, in run
    log.error("failed to communicate with featurehub", err)
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/hodam/.pyenv/versions/3.11.0/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/hodam/.pyenv/versions/ff_proxy/lib/python3.11/site-packages/concurrent_log_handler/__init__.py", line 400, in emit
    self.handleError(record)
Message: 'failed to communicate with featurehub'
Arguments: (ProtocolError("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read)),)
`

Additionally, I have a task that updates the cache. When the task runs on a pod with numerous clients, I'm unable to get the value of the feature flags.

I used your examples to create the proxy. If more information is needed, please let me know
Thanks!

**Comment by rvowles** [comment]
Hi there, do you mean an external cache from the running SDK? When the SDK runs, it connects to the Feature Hub server (either by SSE, which I think you are using here?) or by a simple GET request and then caches it inside the SDK. When apps ask for feature values, it always comes from the cache. So in a standard Web application, all of the running threads would be able to use the same cache.

The purpose of using Streaming on your servers is to ensure they get the updates into the SDK's cache close to immediately.  You can instead use the Polling mechanism which will cause the local cache to use the simple GET and be updated once every period of time (say 30 seconds). 

The logs you post seem to indicate some transient issues with the FH Server, like your app is losing connection to it? This should just be telling you that its having trouble connecting, but it shouldn't stop the connection. Do you find you lose connection and then it never restarts? I'm not sure if it is simply that it is logging the error or its actually not doing the right thing that is causing the problem?

**Comment by hodamarr** [comment]
Hi - thank you for the quick response. Where can I find a reference for a simple API request instead of using SSE? Thank you

**Comment by rvowles** [comment]
Hiya again, you can use the https://github.com/featurehub-io/featurehub-python-sdk/blob/main/featurehub_sdk/featurehub_config.py#L114 - method - i.e. config.use_polling_edge_service() (or you can pass an optional interval or use the one in an env var)
